### ISSUE TITLE
Build error: no matching function for call to 'isfinite'

### ISSUE THREAD

**Issue by shiba24** [ImperialCollegeLondon/EventEMin#2]
Hi, I am trying to build the latest version of this repository and getting a bug.

My environment is:

```
Ubuntu 20.04.3 
libeigen3-dev 3.4.0-1~focal
```

The command is:

```shell
$ cmake .. -DEventEMin_BATCH_MODE=ON
-- The CXX compiler identification is GNU 9.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
OpenMP found
-- Found OpenCV: /usr (found version "4.2.0") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found GSL: /usr/include (found version "2.5") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/shintaro/work/EventEMin/build
➜  build git:(master) make

$ make
```

The error is:

```shell
/home/shintaro/work/EventEMin/test/main_test_sequence_3d.cpp:107:79:   required from here
/usr/include/eigen3/Eigen/src/Core/MathFunctions.h:989:39: error: no matching function for call to ‘isfinite(const Eigen::AutoDiffScalar<Eigen::Matrix<float, 6, 1, 0, 6, 1> >&)’
  989 |     return isfinite EIGEN_NOT_A_MACRO (x);
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
In file included from /home/shintaro/work/EventEMin/include/EventEMin/convolution.h:6,
                 from /home/shintaro/work/EventEMin/include/EventEMin.h:4,
                 from /home/shintaro/work/EventEMin/test/main_test_sequence_3d.cpp:5:
/usr/include/c++/9/cmath:578:5: note: candidate: ‘template<class _Tp> constexpr typename __gnu_cxx::__enable_if<std::__is_integer<_Tp>::__value, bool>::__type std::isfinite(_Tp)’
  578 |     isfinite(_Tp __x)
      |     ^~~~~~~~
```

Could you help me?

**Comment by umgnunes** [comment]
Hello!

I guess that this was something introduced in version 3.4 of Eigen since I had to install it to reproduce this error.

I am not going to be able to dive into this issue soon. So in the meantime, I suggest you install version 3.3 and let me know if you still encounter any issues.

**Comment by shiba24** [comment]
Thank you for the quick reply. I still have two questions:

1. I'm using `sudo apt install libeigen3-dev` and the current version installed is 3.4. I understand you are busy but would appreciate if you can take a look for the 3.4 compatibility. Downgrading Eigen version is not easy because many other libraries also depends on Eigen.. (it's actually not a question but a favor, sorry 🙇 )

2. I just tried 3.3.9 with my old laptop, and got another error. Do you know this? For some reason I disable OpenMP for the compilation below: `cmake .. -DEventEMin_USE_OPENMP=OFF -DEventEMin_BATCH_MODE=ON`

```
In file included from /Users/shiba24/work/EventEMin/test/main_homography.cpp:1:
In file included from /Users/shiba24/work/EventEMin/include/EventEMin.h:4:
/Users/shiba24/work/EventEMin/include/EventEMin/convolution.h:250:19: error: no matching member function for call to 'block'
    val_.template block(ind[0], ind[1], kernel.rows(), kernel.cols()) +=
    ~~~~~~~~~~~~~~^~~~~
/opt/homebrew/include/eigen3/Eigen/src/Core/../plugins/BlockMethods.h:815:50: note: candidate template ignored: couldn't infer template argument 'NRows'
inline typename FixedBlockXpr<NRows,NCols>::Type block(Index startRow, Index startCol,
                                                 ^
/opt/homebrew/include/eigen3/Eigen/src/Core/../plugins/BlockMethods.h:823:61: note: candidate template ignored: couldn't infer template argument 'NRows'
inline const typename ConstFixedBlockXpr<NRows,NCols>::Type block(Index startRow, Index startCol,
                                                            ^
/opt/homebrew/include/eigen3/Eigen/src/Core/../plugins/BlockMethods.h:780:50: note: candidate function template not viable: requires 2 arguments, but 4 were provided
inline typename FixedBlockXpr<NRows,NCols>::Type block(Index startRow, Index startCol)
                                                 ^
/opt/homebrew/include/eigen3/Eigen/src/Core/../plugins/BlockMethods.h:788:61: note: candidate function template not viable: requires 2 arguments, but 4 were provided
inline const typename ConstFixedBlockXpr<NRows,NCols>::Type block(Index startRow, Index startCol) const
```


Which exact version of Eigen do you use/test?

Best,

**Comment by umgnunes** [comment]
Hi!

> 1. I'm using sudo apt install libeigen3-dev and the current version installed is 3.4. I understand you are busy but would appreciate if you can take a look for the 3.4 compatibility. Downgrading Eigen version is not easy because many other libraries also depends on Eigen.. (it's actually not a question but a favor, sorry )

I took a quick look at the errors, but I am afraid it is some issue between the JacobiSVD class from Eigen 3.4, and the AutoDiff module (which is sadly unsupported). This is why it may take some time to solve it.

In the meantime, if you are worried about maintaining multiple Eigen versions, there are multiple ways you can still have the most recent version of Eigen system-wide and have a local one that is downgraded for compatibility, e.g.:

- Follow the steps to download the Eigen repo in the [README](https://github.com/ImperialCollegeLondon/EventEMin/blob/master/README.md) file, but instead of just running `cmake ..`, run `cmake .. -DCMAKE_INSTALL_PREFIX=my/path`. For example, I have a local version installed at `~/.local`, by running `cmake -DCMAKE_INSTALL_PREFIX=~/.local`, and then `make install` (no need for sudo).
- I suggest reverting to 3.3.9. (see below my response to your second point), i.e., `git checkout 0fd6b4f7`, and only the install locally.
- Then, inside the EventEMin repo build directory, run `cmake .. YOUR_OPTIONS -DEigen3_DIR=~/.local/share/eigen3/cmake/`, if you have also installed Eigen in the `~/.local` directory.

> 2. I just tried 3.3.9 with my old laptop, and got another error. Do you know this? For some reason I disable OpenMP for the compilation below: cmake .. -DEventEMin_USE_OPENMP=OFF -DEventEMin_BATCH_MODE=ON

I could not reproduce the error you reported using Eigen 3.3.9. However, I have made some changes, which should fix the issue you report. Pull the changes and let me know otherwise.

> Which exact version of Eigen do you use/test?

I started developing this repo using version 3.3.7., but I compile it with version 3.3.9. just fine.

**Comment by shiba24** [comment]
Understand, and thank you for your help!
Now, with the latest commit and Eigen 3.3.9, it is working on my laptop :)
Thanks again!
