### ISSUE TITLE
Issue running example

### ISSUE THREAD

**Issue by klarala** [ImperialCollegeLondon/EventEMin#5]
Hi,

Thank you for your code.

I am trying it out and I managed to install everything with no problems.
However, I am trying to run the sequences test in batch mode, as written in readme:
[ ~/EventEMin/bin$ ./example_test_sequence ../dataset/poster_rotation 20000 ../dataset/poster_rotation/estimates approx_tsallis_2 ]
and nothing happens, only a blank txt document is created ( EventEMin/dataset/poster_rotation/estimates/approx_tsallis_2_estimates.txt ).

I ran cmake like this: cmake .. -DEventEMin_BATCH_MODE=ON
Running examples such as ./example_rotation seems to work well.

Am I doing something wrong?

**Comment by umgnunes** [comment]
Hi!

The example data provided in the [dataset](https://github.com/ImperialCollegeLondon/EventEMin/tree/master/dataset) folder are only meant to be used to test if everything is working fine, which for you it is since you can run ./example_rotation. They do not contain the full sequences.

To run ./example_test_sequence, you need to download the sequences of interest from [http://rpg.ifi.uzh.ch/davis_data.html](http://rpg.ifi.uzh.ch/davis_data.html), as mentioned in the [README](https://github.com/ImperialCollegeLondon/EventEMin/tree/master#test-sequences).

Hope this helps. Let me know otherwise.

**Comment by klarala** [comment]
Hi!

Thank you for your response.

I downloaded the dataset and ran it again, but I get an error because I don't have enough RAM on this machine, so I will try with a different one.

I also tried running ./example_test_sequence_3d and I don't get any errors, but all the outputs are the same (except for the timestamp):
minimum found at:
1e-06 1e-06 1e-06 1e-06 1e-06 1e-06
ts: 0.096616, vars: 1e-06 1e-06 1e-06 1e-06 1e-06 1e-06
1, 1: -0 0
-0 -0 -0 -0 -0 -0

**Comment by umgnunes** [comment]
For the 3D case: "The events should already be undistorted and augmented with depth". This means that, besides the events having to be already undistorted, each row of the events.txt file should have an additional column corresponding to the depth of each event. Have you done that?
Do you still have the same issue when you just run `./example_6dof`?

**Comment by klarala** [comment]
Hi,

Thanks again for your assistance with this.

I haven't added the depth data. Could you advise on how to obtain or estimate the required depth data for datasets such as poster_rotation from https://rpg.ifi.uzh.ch/davis_data.html for example ?

`./example_6dof` works fine.

Thanks for your help.

**Comment by umgnunes** [comment]
There is no appropriate way to obtain or estimate the depth for that dataset. That is why other datasets are available, which provide depth measurements.

Since there are no issues regarding the code, I will close this issue. Please open it again or a new one if any code issue arises. Thanks for your interest.
